name: Brakeman
 
on:

  pull_request:

    paths:

      - '**/*.rb' # Trigger only when Ruby files are modified
 
jobs:

  brakeman:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up Ruby

        uses: ruby/setup-ruby@v1

        with:

          ruby-version: 3 # Or specify your desired Ruby version

      - name: Install brakeman 5.4.1
        run: gem install brakeman -v 5.4.1

      - name: Get modified files

        id: get_modified_files

        run: echo "::set-output name=files::$(git diff --name-only origin/main...$GITHUB_HEAD_REF | grep '\.rb$')"

      - name: Run Brakeman

        run: |

          echo "${{ steps.get_modified_files.outputs.files }}" | xargs -I{} brakeman {}
