name: Run Ruby script

on:
  push:
    branches:
      - main

jobs:
  run_ruby_script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Run Ruby script
      run: |
        ruby my_script.rb