# name: Checklist Validation

# on:
#   pull_request:
#     types:
#       - opened
#       - edited
#       - synchronize

# jobs:
#   validateChecklist:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check for Checklist Completion
#         run: |
#           checklist_completed=$(grep -c '^\s*-\s*\[x\]'.github/PULL_REQUEST_TEMPLATE.md || true)
#           if [ "$checklist_completed" -eq 0 ]; then
#             echo "error: PR checklist is not completed. Please make sure all checkboxes are marked."
#             exit 1
#           else
          
#           fi
name: PR Checklist Validation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Checklist Validator
        uses: ./.github/actions/checklist-validator
