# name: Pull Request Validation
# on:
#   pull_request:
#     types:
#       - opened
#       - edited
#       - synchronize
# jobs:
#   validate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Pull Request Template
#         id: pr_template
#         uses: actions/github-script@v5
#         with:
#           script: |
#              const prTitle = context.payload.pull_request.title;
#               const ticketRegex = /\bCYNCS-[0-9]+\b/;
#               if (!ticketRegex.test(prTitle)) {
#                   core.setFailed('Error: Ticket number not found in commit message.');
#                   process.exit(1); // Exit with failure status
#               }



name: Pull Pr Request Validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Template
        id: pr_template
        uses: actions/github-script@v5
        with:
          script: |
             const prTitle = context.payload.pull_request.title;
              const ticketRegex = /\b(CYNCS|CYNCPS|FACT|CV|CAS)-[0-9]+\b/;
               if (!ticketRegex.test(prTitle)) {
                   core.setFailed('Ticket number not found in commit message OR commit message is not in proper formate');
                   process.exit(1); // Exit with failure status
               }