name: Pull Request Validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Template
        id: pr_template
        uses: actions/github-script@v5
        with:
          script: |
            const prTemplate = context.payload.pull_request.commit_message;
            const ticketRegex = /\bCYNCS-[0-9]+\b/;
            if (!ticketRegex.test(prTemplate)) {
                core.setFailed('Error: Ticket number not found in commit message.');
            }
