name: Disable Merge Button on Failed Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]

jobs:
  check_status:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get pull request details
        id: pr_details
        run: |
          gem install octokit
          ruby << EOF
          require 'octokit'
          
          client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
          pr_details = client.pull_request("#{ENV['GITHUB_REPOSITORY']}", "#{ENV['GITHUB_EVENT_NUMBER']}")
          checks_failed = pr_details.statuses.any? { |status| status.state == 'failure' }
          
          if checks_failed
            puts "At least one workflow check failed"
            exit 1
          end
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable merge button if any workflow checks failed
        if: steps.pr_details.outcome == 'failure'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"
          
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            -d '{"restrictions": {"users": [], "teams": [], "apps": ["pull-request-checker"]}}' \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER"

