name: Example Workflow
 
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  get_changed_files:
    name: Get Changed Files
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
 
      - name: Retrieve list of changed files
        id: get_files
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/pull/${{ github.event.pull_request.number}}/merge:
          git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} > changed_files.txt
        continue-on-error: true
 
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
 
      - name: Run Ruby script
        run: ruby script22.rb
        env:
          CHANGED_FILES: ${{ steps.get_files.outputs.stdout }}