name: Pull Request Validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Template
        id: pr_template
        uses: actions/github-script@v5
        with:
          script: |
            const requiredFields = ['Description','File Changes','Before Fix','After Fix','Impacted areas','Brakeman Report','OverCommit Report','Checklist'];
            const prTemplate = context.payload.pull_request.body;
            const missingFields = requiredFields.filter(field => !prTemplate.includes(field));
            if (missingFields.length > 0) {
              core.setFailed(`Pull request template is missing required fields: ${missingFields.join(', ')}`);
            }
