
name: Pull Request Validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Template
        id: pr_template
        uses: actions/github-script@v5
        with:
          screquired_fields = ['Title', 'Description', 'Related Issues', 'Checklist']
missing_fields = required_fields.reject { |field| pr_template_body.include?(field) }
if missing_fields.any?
  error_message = "Pull request template is missing required fields: #{missing_fields.join(', ')}"
  flash[:error] = error_message
end




