name: Pull Request Validation
on:
  pull_request:
    types:
      - opened
      - creating
      - edited
      - synchronize
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Template
        id: pr_template
        uses: actions/github-script@v5
        with:
          script: |
            const prTemplate = context.payload.pull_request.body;
            if(prTemplate.indexOf('[ ]') && prTemplate.indexOf('[ ]') != -1)
            {
              core.setFailed('PR checklist is incomplete. Please mark all checkboxes');
            }
